### ISSUE TITLE
Suggestion: Customizable "typing"

### ISSUE THREAD

**Issue by Fezalion** [GriefMoDz/smart-typers#5] opened 2020-10-25 20:15 UTC
Customizable "typing" message if possible, for example:
**abc123** is simping...

**Comment by GriefMoDz** [comment] 2020-10-25 23:30
Thanks for the suggestion! However, it seems you've either missed or haven't reviewed most of the options available on the settings page; setting a custom typing message has been an active feature since version `0.2.2` (https://github.com/GriefMoDz/smart-typers/commit/1a62ecaf61f5e33a1d8cbbf6def4f1cc7aafff86) released on July 7th, 2020.

Below is a screenshot showing a custom typing format that is inline with the example that you've provided.
<img src="https://user-images.githubusercontent.com/12791846/97121711-75818600-1774-11eb-99b7-f35f16bec761.png" width="500">

If you're unable to see this setting please ensure you're up-to-date, or feel free to reach me on the Powercord server.

I'll now be closing this issue as it is a duplicate of one of the features discussed in #1. Cheers!

**Closed as completed by GriefMoDz** 2020-10-25 23:30 UTC
Labels: duplicate
